# Site settings
title: "vmurahari log"
description: "thoughts on engineering leadership, code, culture"
baseurl: "/log/" # begin with /repo-name if use as project, else leave empty for gh-pages
url: "" # default is empty
author: "vmurahari"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave empty to disable it
google_analytics:
disqus_shortname: hnbloggithub
